server:
  port: 8086
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1209
    url: jdbc:mysql://localhost:3306/shequ-user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #redis
  redis:
    host: 10.2.87.200
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

#小程序配置
wx:
  open:
    app_id: wx98b13e4f356be0e7
    app_secret: 2f59de4e543881cf65c91cd5fbefe96a

mybatis-plus:
  type-enums-package: io.xccit.store.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl