spring:
  application:
    name: service-home
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847/nacos
        username: nacos
        password: nacos