server:
  port: 8087

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 50000
        read-timeout: 50000

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    url: 10.2.87.200
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
