server:
  port: 8081

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-acl?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1209
  #JSON返回的时间格式
  jackson:
    time-zone: GMT+8
    date-format: YYYY-MM-DD HH:mm:ss
