server:
  port: 8085

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: io.xccit.store.enums

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-activity?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1209

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
