spring:
  application:
    name: service-sys
  profiles:
    active: dev
  # SpringCloud
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        contextPath: /nacos