server:
  port: 8083

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/shequ-product?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1209
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  # 地域
  endpoint: your endpoint
  # AccessKey
  accessKeyId: your keyid
  accessKeySecret: your keySecret
  # bucket名称
  bucketName: your bucketName
